import { useEffect, useRef, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Check, Clock3, Copy, Download, Eye, FileClock, Link2, LoaderCircle, LockKeyhole, MessageSquare, MoreHorizontal, Reply, RotateCcw, Send, ShieldCheck, UserRound, X } from 'lucide-react'
import { toast } from 'sonner'
import { api, get, patch, post, remove } from '@/lib/api'
import { useAuth } from '@/lib/auth'
import { shortDate } from '@/lib/format'
import { useI18n } from '@/i18n/context'
import { DatePicker } from '@/components/date-picker'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import type { ViewerAnchor } from '@/components/file-viewer'
import { formatBytes, type FileComment, type FileItem, type FileVersion } from './types'

type Access = { visibility: string; inherit_permissions: boolean; members: Array<{ user_id: string; name: string; email: string; brand_role: string; file_role: string | null }> }
type Activity = { id: string; action: string; metadata: string; actor_name: string | null; created_at: string }
type ShareLink = { id: string; allow_download: number; expires_at: string | null; created_at: string; revoked_at: string | null; access_count: number; password_required: number }

export function FileDetailsPanel({ brandId, item, onClose, onChanged, initialTab = 'details', pendingAnchor, onAnchorConsumed }: { brandId: string; item: FileItem; onClose?: () => void; onChanged: () => void; initialTab?: string; pendingAnchor?: ViewerAnchor | null; onAnchorConsumed?: () => void }) {
  const { t } = useI18n()
  const { user } = useAuth()
  const [tab, setTab] = useState(initialTab)
  const comments = useQuery({ queryKey: ['file-comments', brandId, item.id], queryFn: () => get<FileComment[]>(`/api/brands/${brandId}/files/${item.id}/comments`), enabled: item.effective_role !== 'viewer' })
  const versions = useQuery({ queryKey: ['file-versions', brandId, item.id], queryFn: () => get<FileVersion[]>(`/api/brands/${brandId}/files/${item.id}/versions`), enabled: item.kind === 'file' })
  const activity = useQuery({ queryKey: ['file-activity', brandId, item.id], queryFn: () => get<Activity[]>(`/api/brands/${brandId}/files/${item.id}/activity`) })
  const access = useQuery({ queryKey: ['file-access', brandId, item.id], queryFn: () => get<Access>(`/api/brands/${brandId}/files/${item.id}/access`) })
  const shares = useQuery({ queryKey: ['file-shares', brandId, item.id], queryFn: () => get<ShareLink[]>(`/api/brands/${brandId}/files/${item.id}/shares`), enabled: item.effective_role === 'manager' })
  useEffect(() => { if (pendingAnchor) setTab('comments') }, [pendingAnchor])
  return <div className="flex h-full min-h-0 flex-col bg-card" aria-label={t('File details')}>
    <div className="flex items-start gap-3 border-b p-4"><FileTypeMark item={item} /><div className="min-w-0 flex-1"><h2 className="truncate font-medium" translate="no">{item.name}</h2><p className="text-xs text-muted-foreground">{item.kind === 'folder' ? t('Folder') : `${formatBytes(item.size)} · ${item.current_version?.mime_type ?? item.mime_type ?? t('Unknown type')}`}</p></div>{onClose ? <Button size="icon-sm" variant="ghost" onClick={onClose} aria-label={t('Close details')}><X /></Button> : null}</div>
    <Tabs value={tab} onValueChange={(value) => setTab(String(value))} className="min-h-0 min-w-0 flex-1 gap-0"><TabsList variant="line" className="w-full shrink-0 justify-start overflow-x-auto overflow-y-hidden border-b px-3 py-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><TabsTrigger value="details">{t('Details')}</TabsTrigger><TabsTrigger value="activity">{t('Activity')}</TabsTrigger><TabsTrigger value="comments">{t('Comments')}</TabsTrigger><TabsTrigger value="access">{t('Access')}</TabsTrigger>{item.kind === 'file' ? <TabsTrigger value="versions">{t('Versions')}</TabsTrigger> : null}</TabsList>
      <TabsContent value="details" className="min-h-0 overflow-y-auto p-4"><Details item={item} brandId={brandId} onChanged={onChanged} /></TabsContent>
      <TabsContent value="activity" className="min-h-0 overflow-y-auto p-4"><ActivityList rows={activity.data ?? []} loading={activity.isLoading} /></TabsContent>
      <TabsContent value="comments" className="flex min-h-0 flex-col"><Comments brandId={brandId} item={item} rows={comments.data ?? []} loading={comments.isLoading} userId={user?.id ?? ''} onChanged={() => void comments.refetch()} pendingAnchor={pendingAnchor} onAnchorConsumed={onAnchorConsumed} /></TabsContent>
      <TabsContent value="access" className="min-h-0 overflow-y-auto p-4"><AccessPanel brandId={brandId} item={item} value={access.data} shares={shares.data ?? []} onChanged={() => { void access.refetch(); void shares.refetch(); onChanged() }} /></TabsContent>
      {item.kind === 'file' ? <TabsContent value="versions" className="min-h-0 overflow-y-auto p-4"><Versions brandId={brandId} item={item} rows={versions.data ?? []} loading={versions.isLoading} onChanged={() => { void versions.refetch(); onChanged() }} /></TabsContent> : null}
    </Tabs>
  </div>
}

function Details({ item, brandId, onChanged }: { item: FileItem; brandId: string; onChanged: () => void }) {
  const { t } = useI18n()
  const [description, setDescription] = useState(item.description ?? '')
  useEffect(() => setDescription(item.description ?? ''), [item.description])
  const rows = [{ label: t('Owner'), value: item.creator?.name ?? t('Unknown') }, { label: t('Created'), value: shortDate(item.created_at) }, { label: t('Modified'), value: shortDate(item.updated_at) }, { label: t('Size'), value: item.kind === 'folder' ? '—' : formatBytes(item.size) }, { label: t('Access'), value: item.visibility === 'brand' ? t('Brand members') : t('Restricted') }, { label: t('Role'), value: t(roleLabel(item.effective_role)) }, { label: t('Version'), value: item.current_version ? `v${item.current_version.version_number}` : '—' }]
  return <div className="space-y-5"><div><Label htmlFor={`description-${item.id}`}>{t('Description')}</Label><Textarea id={`description-${item.id}`} className="mt-2 min-h-24" value={description} onChange={(event) => setDescription(event.target.value)} placeholder={t('Add context for collaborators…')} disabled={!['editor', 'manager'].includes(item.effective_role)} /><Button className="mt-2" size="sm" disabled={description === (item.description ?? '') || !['editor', 'manager'].includes(item.effective_role)} onClick={async () => { await patch(`/api/brands/${brandId}/files/${item.id}`, { description }); toast.success(t('Description saved')); onChanged() }}>{t('Save')}</Button></div><Separator />
    <dl className="space-y-3">{rows.map((row) => <div key={row.label} className="grid grid-cols-[6rem_1fr] gap-3 text-sm"><dt className="text-muted-foreground">{row.label}</dt><dd className="min-w-0 truncate" translate="no">{row.value}</dd></div>)}</dl>
    {item.current_version ? <div className="rounded-lg border bg-muted/30 p-3 text-xs"><strong>{t('Integrity')}</strong><p className="mt-1 text-muted-foreground">{t('Scanned · immutable version')}</p><code className="mt-2 block truncate" translate="no">SHA-256 {item.current_version.sha256 || t('Legacy file')}</code></div> : null}
  </div>
}

function ActivityList({ rows, loading }: { rows: Activity[]; loading: boolean }) {
  const { t } = useI18n()
  if (loading) return <Loading />
  if (!rows.length) return <Empty icon={Clock3} title={t('No activity yet')} detail={t('File events will appear here.')} />
  return <ol className="space-y-1">{rows.map((row) => <li key={row.id} className="relative border-s pb-5 ps-5 last:pb-0"><span className="absolute -start-1.5 top-1 size-3 rounded-full border-2 border-card bg-primary" /><p className="text-sm"><strong translate="no">{row.actor_name ?? t('System')}</strong> {t(activityLabel(row.action))}</p><time className="text-xs text-muted-foreground">{shortDate(row.created_at)}</time></li>)}</ol>
}

function Comments({ brandId, item, rows, loading, userId, onChanged, pendingAnchor, onAnchorConsumed }: { brandId: string; item: FileItem; rows: FileComment[]; loading: boolean; userId: string; onChanged: () => void; pendingAnchor?: ViewerAnchor | null; onAnchorConsumed?: () => void }) {
  const { t } = useI18n()
  const [message, setMessage] = useState('')
  const [privateNote, setPrivateNote] = useState(false)
  const [replyTo, setReplyTo] = useState<string | null>(null)
  const [mentionId, setMentionId] = useState('')
  const members = useQuery({ queryKey: ['file-comment-members', brandId, item.id], queryFn: () => get<Access>(`/api/brands/${brandId}/files/${item.id}/access`) })
  const roots = rows.filter((row) => !row.parent_id)
  async function submit() {
    if (!message.trim()) return
    await post(`/api/brands/${brandId}/files/${item.id}/comments`, { body: message.trim(), parent_id: replyTo, visibility: privateNote ? 'private' : 'team', version_id: pendingAnchor && pendingAnchor.kind !== 'file' ? item.current_version_id : null, anchor: pendingAnchor ?? { kind: 'file' }, mention_ids: mentionId ? [mentionId] : [] })
    setMessage(''); setReplyTo(null); setMentionId(''); onAnchorConsumed?.(); onChanged(); toast.success(t('Comment added'))
  }
  return <><div className="min-h-0 flex-1 overflow-y-auto p-4">{loading ? <Loading /> : !roots.length ? <Empty icon={MessageSquare} title={t('Start a discussion')} detail={t('Comments and private notes stay with the file.')} /> : <div className="space-y-3">{roots.map((comment) => <Comment key={comment.id} comment={comment} replies={rows.filter((row) => row.parent_id === comment.id)} currentUserId={userId} onReply={() => setReplyTo(comment.id)} onChanged={onChanged} brandId={brandId} item={item} />)}</div>}</div>
    {item.effective_role !== 'viewer' ? <div className="border-t p-3">{pendingAnchor ? <div className="mb-2 flex items-center gap-2 rounded-md bg-primary/8 px-2 py-1.5 text-xs"><MessageSquare className="size-3.5" />{t('Context attached to this comment')}<Button className="ms-auto" size="icon-xs" variant="ghost" onClick={onAnchorConsumed} aria-label={t('Remove context')}><X /></Button></div> : null}{replyTo ? <div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><Reply className="size-3.5" />{t('Replying to a thread')}<Button className="ms-auto h-auto p-0 text-xs underline" size="xs" variant="link" onClick={() => setReplyTo(null)}>{t('Cancel')}</Button></div> : null}<Textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={privateNote ? t('Write a private note…') : t('Write a comment…')} className="min-h-20" /><div className="mt-2 flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 text-xs"><Checkbox checked={privateNote} onCheckedChange={(value) => setPrivateNote(Boolean(value))} />{t('Private note')}</label>{!privateNote ? <Select value={mentionId} onValueChange={(value) => setMentionId(String(value))}><SelectTrigger size="sm" className="w-40"><SelectValue placeholder={t('Mention member')} /></SelectTrigger><SelectContent><SelectGroup>{members.data?.members.map((member) => <SelectItem key={member.user_id} value={member.user_id} translate="no">@{member.name}</SelectItem>)}</SelectGroup></SelectContent></Select> : null}<Button className="ms-auto" size="sm" disabled={!message.trim()} onClick={() => void submit()}><Send />{t('Send')}</Button></div></div> : null}</>
}

function Comment({ comment, replies, currentUserId, onReply, onChanged, brandId, item }: { comment: FileComment; replies: FileComment[]; currentUserId: string; onReply: () => void; onChanged: () => void; brandId: string; item: FileItem }) {
  const { t } = useI18n()
  return <article className={`rounded-lg border p-3 ${comment.visibility === 'private' ? 'border-amber-300/60 bg-amber-50/50 dark:border-amber-800 dark:bg-amber-950/20' : 'bg-card'}`}><div className="flex items-start gap-2"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-muted text-xs font-medium" translate="no">{comment.author_name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-xs" translate="no">{comment.author_name}</strong>{comment.visibility === 'private' ? <Badge variant="outline"><LockKeyhole />{t('Private')}</Badge> : null}{comment.resolved_at ? <Badge variant="secondary"><Check />{t('Resolved')}</Badge> : null}<time className="ms-auto text-[0.65rem] text-muted-foreground">{shortDate(comment.created_at)}</time></div><p className="mt-1 whitespace-pre-wrap text-sm" translate="no">{comment.body}</p><div className="mt-2 flex gap-1"><Button size="xs" variant="ghost" onClick={onReply}><Reply />{t('Reply')}</Button>{!comment.resolved_at && (comment.author_id === currentUserId || ['editor', 'manager'].includes(item.effective_role)) ? <Button size="xs" variant="ghost" onClick={async () => { await patch(`/api/brands/${brandId}/files/${item.id}/comments/${comment.id}`, { resolved: true }); onChanged() }}><Check />{t('Resolve')}</Button> : null}</div></div></div>{replies.length ? <div className="mt-3 space-y-2 border-s ps-3">{replies.map((reply) => <div key={reply.id} className="text-sm"><div className="flex gap-2"><strong className="text-xs" translate="no">{reply.author_name}</strong><time className="text-[0.65rem] text-muted-foreground">{shortDate(reply.created_at)}</time></div><p className="mt-1 whitespace-pre-wrap" translate="no">{reply.body}</p></div>)}</div> : null}</article>
}

function AccessPanel({ brandId, item, value, shares, onChanged }: { brandId: string; item: FileItem; value?: Access; shares: ShareLink[]; onChanged: () => void }) {
  const { t } = useI18n()
  const [shareOpen, setShareOpen] = useState(false)
  const manager = item.effective_role === 'manager'
  return <div className="space-y-5"><div className="rounded-lg border p-3"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 text-primary" /><div><strong className="text-sm">{item.visibility === 'brand' ? t('Brand members') : t('Restricted access')}</strong><p className="mt-1 text-xs text-muted-foreground">{item.inherit_permissions ? t('Folder permissions are inherited.') : t('Permission inheritance is disabled for this subtree.')}</p></div></div>{manager ? <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={async () => { await patch(`/api/brands/${brandId}/files/${item.id}`, { visibility: item.visibility === 'brand' ? 'restricted' : 'brand' }); onChanged() }}>{item.visibility === 'brand' ? t('Make restricted') : t('Share with brand')}</Button><Button size="sm" variant="outline" onClick={async () => { if (item.inherit_permissions && !window.confirm(t('Breaking inheritance creates a separately managed subtree. Continue?'))) return; await patch(`/api/brands/${brandId}/files/${item.id}`, { inherit_permissions: !item.inherit_permissions }); onChanged() }}>{item.inherit_permissions ? t('Break inheritance') : t('Restore inheritance')}</Button></div> : null}</div>
    <div><div className="mb-2 flex items-center justify-between"><h3 className="text-sm font-medium">{t('People with access')}</h3></div><div className="divide-y rounded-lg border">{value?.members.map((member) => <div key={member.user_id} className="flex items-center gap-2 p-2"><span className="grid size-8 place-items-center rounded-full bg-muted"><UserRound className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm" translate="no">{member.name}</p><p className="truncate text-xs text-muted-foreground" translate="no">{member.email}</p></div>{manager ? <Select value={member.file_role ?? 'inherited'} onValueChange={async (next) => { await api(`/api/brands/${brandId}/files/${item.id}/access/${member.user_id}`, { method: 'PUT', body: JSON.stringify({ role: next === 'inherited' ? null : next }) }); onChanged() }}><SelectTrigger size="sm" className="w-28"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="inherited">{t('Inherited')}</SelectItem><SelectItem value="viewer">{t('Viewer')}</SelectItem><SelectItem value="commenter">{t('Commenter')}</SelectItem><SelectItem value="editor">{t('Editor')}</SelectItem><SelectItem value="manager">{t('Manager')}</SelectItem></SelectGroup></SelectContent></Select> : <span className="text-xs text-muted-foreground">{t(roleLabel((member.file_role ?? 'viewer') as FileItem['effective_role']))}</span>}</div>)}</div></div>
    <Separator /><div><div className="mb-2 flex items-center justify-between"><div><h3 className="text-sm font-medium">{t('External links')}</h3><p className="text-xs text-muted-foreground">{t('Anonymous visitors cannot discover other brand files.')}</p></div>{manager ? <Button size="sm" onClick={() => setShareOpen(true)}><Link2 />{t('Create link')}</Button> : null}</div>{shares.length ? <div className="space-y-2">{shares.filter((share) => !share.revoked_at).map((share) => <div key={share.id} className="flex items-center gap-2 rounded-lg border p-2"><Link2 className="size-4 text-primary" /><div className="min-w-0 flex-1"><p className="text-xs font-medium">{share.expires_at ? t('Expires {date}', { date: shortDate(share.expires_at) }) : t('No expiry')}</p><p className="text-[0.65rem] text-muted-foreground">{share.password_required ? t('Password protected') : t('No password')} · {share.allow_download ? t('Downloads allowed') : t('View only')} · {t('{count} visits', { count: share.access_count })}</p></div><DropdownMenu><DropdownMenuTrigger render={<Button size="icon-sm" variant="ghost" aria-label={t('Link actions')} />}><MoreHorizontal /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuGroup><DropdownMenuItem variant="destructive" onClick={async () => { await remove(`/api/brands/${brandId}/files/${item.id}/shares/${share.id}`); onChanged() }}>{t('Revoke link')}</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu></div>)}</div> : <p className="rounded-lg border border-dashed p-4 text-center text-xs text-muted-foreground">{t('No active external links')}</p>}</div><ShareDialog open={shareOpen} onOpenChange={setShareOpen} brandId={brandId} item={item} onCreated={onChanged} />
  </div>
}

function ShareDialog({ open, onOpenChange, brandId, item, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; brandId: string; item: FileItem; onCreated: () => void }) {
  const { t } = useI18n()
  const [password, setPassword] = useState('')
  const [expires, setExpires] = useState('')
  const [download, setDownload] = useState(false)
  const [created, setCreated] = useState('')
  async function create() {
    const result = await post<{ url: string }>(`/api/brands/${brandId}/files/${item.id}/shares`, { password: password || undefined, expires_at: expires ? new Date(`${expires}T23:59:59`).toISOString() : null, allow_download: download })
    setCreated(result.url); onCreated()
  }
  return <Dialog open={open} onOpenChange={(value) => { onOpenChange(value); if (!value) { setCreated(''); setPassword(''); setExpires(''); setDownload(false) } }}><DialogContent><DialogHeader><DialogTitle>{t('Create secure external link')}</DialogTitle><DialogDescription>{item.kind === 'folder' ? t('The link includes this folder and all descendants that inherit its access. Download permission is off by default.') : t('Download permission is off by default. Links without an expiry or password require extra care.')}</DialogDescription></DialogHeader>{created ? <div className="space-y-3"><Label>{t('Share link')}</Label><div className="flex gap-2"><Input value={created} readOnly translate="no" /><Button size="icon" onClick={() => { void navigator.clipboard.writeText(created); toast.success(t('Link copied')) }} aria-label={t('Copy link')}><Copy /></Button></div></div> : <div className="space-y-4"><div><Label htmlFor="share-expiry">{t('Expiry date (optional)')}</Label><DatePicker id="share-expiry" value={expires} onChange={setExpires} ariaLabel={t('Expiry date (optional)')} className="mt-1.5" /></div><div><Label htmlFor="share-password">{t('Password (optional)')}</Label><Input id="share-password" type="password" className="mt-1.5" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t('At least 8 characters')} /></div><label className="flex items-start gap-2 rounded-lg border p-3 text-sm"><Checkbox checked={download} onCheckedChange={(value) => setDownload(Boolean(value))} /><span><strong>{t('Allow downloads')}</strong><span className="block text-xs text-muted-foreground">{item.kind === 'folder' ? t('Visitors can download the complete folder as a ZIP archive.') : t('Visitors can save original files when enabled.')}</span></span></label>{!expires || !password ? <div className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">{t('Warning: this link is missing an expiry, a password, or both.')}</div> : null}</div>}<DialogFooter>{created ? <Button onClick={() => onOpenChange(false)}>{t('Done')}</Button> : <><Button variant="outline" onClick={() => onOpenChange(false)}>{t('Cancel')}</Button><Button disabled={Boolean(password) && password.length < 8} onClick={() => void create()}>{t('Create link')}</Button></>}</DialogFooter></DialogContent></Dialog>
}

function Versions({ brandId, item, rows, loading, onChanged }: { brandId: string; item: FileItem; rows: FileVersion[]; loading: boolean; onChanged: () => void }) {
  const { t } = useI18n()
  const input = useRef<HTMLInputElement>(null)
  async function uploadVersion(file?: File) {
    if (!file) return
    const data = new FormData(); data.set('file', file)
    await api(`/api/brands/${brandId}/files/${item.id}/versions`, { method: 'POST', body: data }); toast.success(t('New version uploaded')); onChanged()
  }
  if (loading) return <Loading />
  return <div><Input ref={input} type="file" className="hidden" onChange={(event) => void uploadVersion(event.target.files?.[0])} /><Button className="mb-4 w-full" variant="outline" disabled={!['editor', 'manager'].includes(item.effective_role)} onClick={() => input.current?.click()}><FileClock />{t('Upload new version')}</Button><ol className="space-y-2">{rows.map((version) => <li key={version.id} className={`rounded-lg border p-3 ${item.current_version_id === version.id ? 'border-primary/40 bg-primary/5' : ''}`}><div className="flex items-start gap-2"><span className="grid size-8 place-items-center rounded-full bg-muted text-xs font-medium">v{version.version_number}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium" translate="no">{version.original_name}</p><p className="text-xs text-muted-foreground">{formatBytes(version.size)} · {shortDate(version.created_at)}</p><p className="mt-1 text-[0.65rem] text-muted-foreground" translate="no">{version.creator_name ?? t('Unknown')} · {version.scan_state}</p></div>{item.current_version_id === version.id ? <Badge>{t('Current')}</Badge> : ['editor', 'manager'].includes(item.effective_role) ? <Button size="icon-sm" variant="ghost" onClick={async () => { await post(`/api/brands/${brandId}/files/${item.id}/versions/${version.id}/restore`); toast.success(t('Version restored as a new current version')); onChanged() }} aria-label={t('Restore this version')}><RotateCcw /></Button> : null}</div><div className="mt-2 flex gap-2"><Button size="xs" variant="ghost" render={<a href={`/api/brands/${brandId}/files/${item.id}/content?version=${version.id}&download=1`} download />}><Download />{t('Download')}</Button>{item.current_version_id !== version.id && item.effective_role === 'manager' ? <Button size="xs" variant="ghost" className="text-destructive" onClick={async () => { if (!window.confirm(t('Delete this immutable version reference?'))) return; await remove(`/api/brands/${brandId}/files/${item.id}/versions/${version.id}`); onChanged() }}>{t('Delete version')}</Button> : null}</div></li>)}</ol></div>
}

function FileTypeMark({ item }: { item: FileItem }) { return <span className={`grid size-10 shrink-0 place-items-center rounded-lg ${item.kind === 'folder' ? 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300' : 'bg-primary/10 text-primary'}`}>{item.kind === 'folder' ? <FileClock /> : item.preview_kind === 'image' ? <Eye /> : <FileClock />}</span> }
function Loading() { return <div className="grid min-h-32 place-items-center"><LoaderCircle className="size-5 animate-spin text-muted-foreground" /></div> }
function Empty({ icon: Icon, title, detail }: { icon: typeof MessageSquare; title: string; detail: string }) { return <div className="grid min-h-40 place-items-center text-center"><div><Icon className="mx-auto size-7 text-muted-foreground" /><strong className="mt-2 block text-sm">{title}</strong><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div></div> }
function roleLabel(role: FileItem['effective_role']) { return ({ viewer: 'Viewer', commenter: 'Commenter', editor: 'Editor', manager: 'Manager' })[role] }
function activityLabel(action: string) { return ({ upload: 'uploaded this file', create_folder: 'created this folder', update: 'updated file details', rename: 'renamed this item', move: 'moved this item', copy: 'copied this item', star: 'starred this item', unstar: 'removed this item from Starred', trash: 'moved this item to Trash', restore: 'restored this item', upload_version: 'uploaded a new version', restore_version: 'restored an older version', permission: 'changed access', create_link: 'created an external link', revoke_link: 'revoked an external link', comment: 'started a discussion', reply: 'replied to a discussion', resolve_comment: 'resolved a discussion' } as Record<string, string>)[action] ?? 'updated this item' }
