import { useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, BellRing, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Image, Mail, MessageCircle, Send, Smartphone, UsersRound } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth'
import { get, post } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'

type Channel = 'email' | 'sms' | 'whatsapp' | 'push'
type Sender = { id: string; channel: string; display_name: string; address: string; status: string }
const choices: Array<{ channel: Channel; title: string; description: string; icon: typeof Mail; tone: string }> = [
  { channel: 'email', title: 'Email', description: 'Rich newsletters and product announcements', icon: Mail, tone: 'bg-blue-50 text-blue-700' },
  { channel: 'sms', title: 'SMS', description: 'Concise, immediate mobile messages', icon: Smartphone, tone: 'bg-violet-50 text-violet-700' },
  { channel: 'whatsapp', title: 'WhatsApp', description: 'Approved templates and service messages', icon: MessageCircle, tone: 'bg-emerald-50 text-emerald-700' },
  { channel: 'push', title: 'Push', description: 'Browser and mobile application alerts', icon: BellRing, tone: 'bg-amber-50 text-amber-700' },
]

function ChannelPicker() {
  const navigate = useNavigate()
  return <div className="mx-auto max-w-5xl space-y-8 py-4"><div><p className="eyebrow">New campaign</p><h1 className="mt-2 text-3xl font-semibold">Choose a channel</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Each campaign uses one channel, with delivery rules and content designed for that medium. Automations can combine them later.</p></div><div className="grid gap-4 sm:grid-cols-2">{choices.map((item) => <button key={item.channel} onClick={() => navigate(`/campaigns/new/${item.channel}`)} className="group rounded-xl border bg-card p-5 text-start shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><span className={cn('mb-8 grid size-11 place-items-center rounded-xl', item.tone)}><item.icon className="size-5"/></span><h2 className="text-lg font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.description}</p><span className="mt-5 inline-flex items-center text-xs font-medium text-primary">Create {item.title} campaign <span className="ms-1 transition group-hover:translate-x-1">→</span></span></button>)}</div></div>
}

function PhonePreview({ channel, title, body }: { channel: Channel; title: string; body: string }) {
  return <div className="mx-auto w-[260px] rounded-[2.5rem] border-[7px] border-slate-900 bg-slate-50 p-2 shadow-2xl"><div className="mx-auto mb-3 h-4 w-20 rounded-b-xl bg-slate-900"/><div className="rounded-[1.8rem] bg-white p-3"><div className="mb-5 flex items-center gap-2 border-b pb-3"><span className={cn('grid size-8 place-items-center rounded-full', channel === 'whatsapp' ? 'bg-emerald-500 text-white' : channel === 'sms' ? 'bg-violet-500 text-white' : channel === 'push' ? 'bg-amber-400' : 'bg-blue-500 text-white')}>{channel === 'push' ? <BellRing className="size-4"/> : channel === 'email' ? <Mail className="size-4"/> : channel === 'sms' ? <Smartphone className="size-4"/> : <MessageCircle className="size-4"/>}</span><div><strong className="block text-xs">Atlas</strong><span className="block text-[0.6rem] text-muted-foreground">Business account</span></div></div>{channel === 'whatsapp' && <div className="mb-2 grid h-24 place-items-center rounded-lg bg-gradient-to-br from-stone-100 to-amber-100"><Image className="size-8 text-stone-400"/></div>}<div className={cn('rounded-xl p-3 text-xs leading-relaxed', channel === 'whatsapp' ? 'bg-emerald-50' : channel === 'sms' ? 'bg-violet-50' : channel === 'push' ? 'border bg-card shadow' : 'border bg-card')}><strong className="mb-1 block">{title || (channel === 'push' ? 'Your notification title' : 'Atlas update')}</strong>{body || 'Your message preview will appear here.'}<span className="mt-2 block text-end text-[0.55rem] text-muted-foreground">11:30 ✓✓</span></div>{channel === 'whatsapp' && <button className="mt-1 w-full rounded-lg border py-2 text-[0.65rem] font-medium text-primary">Track my order</button>}<div className="h-32"/></div></div>
}

function Composer({ channel }: { channel: Channel }) {
  const { brand } = useAuth(), navigate = useNavigate()
  const [name, setName] = useState(channel === 'whatsapp' ? 'August delivery update' : ''), [purpose, setPurpose] = useState<'marketing' | 'transactional' | 'support'>(channel === 'whatsapp' ? 'transactional' : 'marketing')
  const [title, setTitle] = useState(channel === 'push' ? 'Atlas 4.2 is live' : channel === 'email' ? 'A useful update from Atlas' : '')
  const [body, setBody] = useState(channel === 'whatsapp' ? 'Bonjour {{1}}, votre commande {{2}} sera livrée le {{3}}.' : channel === 'sms' ? 'Atlas members: your early-access selection is ready. Explore it here: https://atlas.test/early' : channel === 'push' ? 'See the faster workspace and new reports.' : 'Hello,\n\nHere is what is new at Atlas this month.')
  const [senderId, setSenderId] = useState(''), [templateName] = useState(channel === 'whatsapp' ? 'delivery_update' : '')
  const senders = useQuery({ queryKey: ['sender-identities', brand?.id, channel], queryFn: () => get<{ data: Sender[] }>(`/api/v2/brands/${brand?.id}/sender-identities?channel=${channel}`).then((item) => item.data), enabled: !!brand })
  const sender = senders.data?.find((item) => item.id === senderId) ?? senders.data?.[0]
  const content = useMemo(() => channel === 'email' ? { channel, subject: title, html: `<p>${body.replaceAll('\n', '<br>')}</p>`, text: body, attachments: [] } : channel === 'sms' ? { channel, body, media: [], shorten_links: true } : channel === 'whatsapp' ? { channel, body, template: templateName ? { name: templateName, language: 'fr', variables: { '1': 'First name', '2': 'Order number', '3': 'Delivery date' } } : undefined, media: [], buttons: [{ type: 'url', label: 'Track my order', value: 'https://example.test/track' }] } : { channel, title, body, target_url: 'https://atlas.test/releases/4-2', data: {} }, [body, channel, templateName, title])
  const save = useMutation({ mutationFn: () => post<{ data: { id: string } }>(`/api/v2/brands/${brand?.id}/campaigns`, { name: name || `${channel} campaign`, channel, purpose, sender_identity_id: sender?.id, content, audience: { contact_ids: [], list_ids: [], excluded_contact_ids: [] }, tracking_policy: { clicks: true, opens: channel === 'email' } }), onSuccess: () => { toast.success('Campaign draft saved'); navigate('/campaigns') }, onError: (error) => toast.error(error instanceof Error ? error.message : 'Unable to save campaign') })
  const smsCount = channel === 'sms' ? Math.max(1, Math.ceil(body.length / (body.length <= 160 ? 160 : 153))) : 1
  return <div className="mx-auto max-w-[1240px] space-y-4 pb-24">
    <div className="flex flex-wrap items-start gap-4"><Button variant="ghost" size="icon" onClick={() => navigate('/campaigns/new')}><ArrowLeft/></Button><div><h1 className="text-2xl font-semibold">Create {choices.find((item) => item.channel === channel)?.title} campaign</h1><p className="mt-1 text-sm text-muted-foreground">Compose a channel-native message for a targeted audience.</p></div><div className="ms-auto flex gap-2"><Button variant="outline" onClick={() => save.mutate()} disabled={save.isPending}>Save draft</Button><Button onClick={() => save.mutate()} disabled={save.isPending}>Review & schedule</Button></div></div>
    <div className="grid grid-cols-4 gap-3 rounded-xl border bg-card px-5 py-3 text-xs">{['Details', 'Audience', 'Content', 'Schedule'].map((step, index) => <div key={step} className={cn('flex items-center gap-2', index === 2 ? 'text-foreground' : 'text-muted-foreground')}><span className={cn('grid size-6 place-items-center rounded-full border', index < 2 && 'border-emerald-200 bg-emerald-50 text-emerald-700', index === 2 && 'border-primary bg-primary text-primary-foreground')}>{index < 2 ? <Check className="size-3"/> : index + 1}</span>{step}<span className="ms-2 hidden h-px flex-1 bg-border sm:block"/></div>)}</div>
    <div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_24rem]">
      <Card><CardContent className="p-0"><div className="grid gap-4 border-b p-4 sm:grid-cols-4"><div><span className="text-[0.68rem] text-muted-foreground">Channel</span><strong className="mt-1 flex items-center gap-1.5 text-sm capitalize">{choices.find((item) => item.channel === channel)?.icon && (() => { const Icon = choices.find((item) => item.channel === channel)!.icon; return <Icon className="size-4"/> })()}{channel}</strong></div><div><span className="text-[0.68rem] text-muted-foreground">Provider</span><strong className="mt-1 block text-sm">{sender ? 'Configured' : 'Sandbox'}</strong></div><div><span className="text-[0.68rem] text-muted-foreground">Sender</span><strong className="mt-1 block truncate text-sm">{sender?.address ?? 'Select sender'}</strong></div><div><Label className="text-[0.68rem] text-muted-foreground">Campaign name</Label><Input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 h-8" placeholder="Campaign name"/></div></div>
        <div className="space-y-5 p-4">
          <div className="grid gap-4 sm:grid-cols-2"><div><Label>Purpose</Label><select className="mt-1 h-9 w-full rounded-md border bg-background px-3 text-sm" value={purpose} onChange={(event) => setPurpose(event.target.value as typeof purpose)}><option value="marketing">Marketing</option><option value="transactional">Transactional</option><option value="support">Support</option></select></div><div><Label>Sender identity</Label><select className="mt-1 h-9 w-full rounded-md border bg-background px-3 text-sm" value={sender?.id ?? ''} onChange={(event) => setSenderId(event.target.value)}><option value="">Default sender</option>{senders.data?.map((item) => <option key={item.id} value={item.id}>{item.display_name} — {item.address}</option>)}</select></div></div>
          {channel === 'whatsapp' && <div><Label>Approved template</Label><div className="mt-1 flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><span className="flex-1">{templateName || 'Session message'}</span>{templateName && <Badge className="bg-emerald-50 text-emerald-700">Approved</Badge>}<ChevronDown className="size-4"/></div></div>}
          {(channel === 'email' || channel === 'push') && <div><Label>{channel === 'email' ? 'Subject' : 'Notification title'}</Label><Input className="mt-1" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={channel === 'email' ? 'Email subject' : 'Push title'}/></div>}
          <div><div className="mb-1 flex items-center justify-between"><Label>{channel === 'whatsapp' ? 'Body (fr)' : 'Message'}</Label><span className="text-[0.68rem] text-muted-foreground">{body.length}/{channel === 'sms' ? 1600 : channel === 'whatsapp' ? 4096 : 10000}</span></div><Textarea value={body} onChange={(event) => setBody(event.target.value)} className="min-h-36"/></div>
          {channel === 'whatsapp' && <div className="grid gap-3 sm:grid-cols-[1fr_15rem]"><button className="flex h-14 items-center gap-3 rounded-lg border px-3 text-start"><span className="grid size-8 place-items-center rounded bg-muted"><Image className="size-4"/></span><span className="text-xs"><strong className="block">delivery_boxes.jpg</strong><span className="text-muted-foreground">1200 × 800</span></span></button><div className="rounded-lg border"><div className="border-b px-3 py-1.5 text-xs">Variables</div>{['First name', 'Order number', 'Delivery date'].map((item, index) => <div key={item} className="flex gap-2 border-b px-3 py-1.5 text-xs last:border-0"><span>{index + 1}</span><span>{item}</span></div>)}</div></div>}
          <div className="flex flex-wrap items-center gap-3 rounded-lg border bg-muted/35 px-3 py-2 text-xs"><CheckCircle2 className="size-4 text-emerald-600"/><span>{channel === 'sms' ? `${smsCount} SMS segment${smsCount > 1 ? 's' : ''} · estimated GSM/UCS billing is checked at send time` : 'All good! Your message is within channel limits.'}</span><Button className="ms-auto" variant="outline" size="sm"><Send/>Send test</Button></div>
        </div>
        <div className="border-t p-4"><h3 className="mb-3 text-sm font-semibold">Audience</h3><div className="grid gap-4 sm:grid-cols-3"><div><span className="text-xs text-muted-foreground">Included</span><strong className="mt-1 flex items-center gap-2 text-sm"><UsersRound className="size-4"/>All consented contacts</strong></div><div><span className="text-xs text-muted-foreground">Excluded</span><strong className="mt-1 block text-sm">Channel opted out</strong></div><div><span className="text-xs text-muted-foreground">Estimated eligible recipients</span><strong className="metric-number mt-1 block text-2xl">8,246</strong></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="flex items-center gap-3 rounded-lg border p-3"><span className="grid size-8 place-items-center rounded-full bg-emerald-50 text-emerald-700"><CheckCircle2 className="size-4"/></span><div className="text-xs"><strong className="block">Consent</strong><span className="text-muted-foreground">Every recipient is checked at queue time</span></div></div><div className="flex items-center gap-3 rounded-lg border p-3"><span className="grid size-8 place-items-center rounded-full bg-blue-50 text-blue-700"><Clock3 className="size-4"/></span><div className="text-xs"><strong className="block">Quiet hours</strong><span className="text-muted-foreground">Recipient timezone is respected</span></div></div></div></div>
      </CardContent></Card>
      <div className="space-y-4 lg:sticky lg:top-20"><Card><CardHeader className="border-b pb-3"><div className="flex gap-8 text-sm"><button className="border-b-2 border-primary pb-2 font-medium text-primary">Preview</button><button className="pb-2 text-muted-foreground">Checks</button></div></CardHeader><CardContent className="bg-gradient-to-b from-slate-50 to-white py-6"><PhonePreview channel={channel} title={title} body={body}/></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Preflight checks</CardTitle></CardHeader><CardContent className="space-y-3 text-xs">{['Content valid', 'Consent verified', 'Provider connected', 'Quiet hours respected'].map((item) => <div key={item} className="flex items-center gap-2"><CheckCircle2 className="size-4 text-emerald-600"/><span>{item}</span><span className="ms-auto text-muted-foreground">Ready</span></div>)}</CardContent></Card></div>
    </div>
    <div className="fixed bottom-0 start-0 end-0 z-20 border-t bg-background/95 p-3 backdrop-blur md:start-[14.25rem]"><div className="mx-auto flex max-w-[1240px] items-center gap-6"><div className="hidden items-center gap-2 sm:flex"><UsersRound className="size-5"/><span><strong className="block text-sm">8,246 recipients</strong><span className="text-xs text-muted-foreground">Estimated</span></span></div><div className="hidden items-center gap-2 sm:flex"><CircleDollarSign className="size-5"/><span><strong className="block text-sm">~€{channel === 'sms' ? '82.46' : channel === 'whatsapp' ? '24.74' : '4.20'}</strong><span className="text-xs text-muted-foreground">Estimated provider cost</span></span></div><div className="ms-auto flex gap-2"><Button variant="outline" onClick={() => navigate('/campaigns/new')}>Back</Button><Button variant="outline" onClick={() => save.mutate()}>Save draft</Button><Button onClick={() => save.mutate()}>Review & schedule</Button></div></div></div>
  </div>
}

export default function ChannelCampaignPage() {
  const { channel } = useParams<{ channel?: string }>()
  if (!channel) return <ChannelPicker/>
  if (!['email', 'sms', 'whatsapp', 'push'].includes(channel)) return <ChannelPicker/>
  return <Composer channel={channel as Channel}/>
}
