import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BellRing, CheckCircle2, Copy, KeyRound, Mail, MessageCircle, Phone, Plus, RefreshCw, Send, Settings2, Smartphone, Webhook } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth'
import { get, post } from '@/lib/api'
import { PageHeader } from '@/components/page-header'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'

type Connection = { id: string; channel: string; provider: string; name: string; status: string; is_default: boolean; last_tested_at?: string; last_error?: string }
const channelIcons = { email: Mail, sms: Smartphone, whatsapp: MessageCircle, push: BellRing, voice: Phone }
const providers: Record<string, Array<{ id: string; name: string; detail: string; fields: string[] }>> = {
  sms: [{ id: 'twilio', name: 'Twilio', detail: 'SMS, MMS, delivery callbacks', fields: ['account_sid', 'auth_token'] }, { id: 'vonage', name: 'Vonage', detail: 'Global SMS delivery', fields: ['api_key', 'api_secret', 'signature_secret'] }],
  whatsapp: [{ id: 'meta', name: 'Meta Cloud API', detail: 'Direct WhatsApp Business Platform', fields: ['phone_number_id', 'access_token', 'app_secret'] }, { id: 'twilio', name: 'Twilio WhatsApp', detail: 'Twilio managed sender', fields: ['account_sid', 'auth_token'] }, { id: 'vonage', name: 'Vonage WhatsApp', detail: 'Vonage Messages API', fields: ['api_key', 'api_secret', 'jwt', 'signature_secret'] }],
  push: [{ id: 'webpush', name: 'Web Push', detail: 'Standards-based VAPID browser push', fields: ['subject', 'public_key', 'private_key'] }, { id: 'fcm', name: 'Firebase Cloud Messaging', detail: 'FCM HTTP v1 for external apps', fields: ['project_id', 'service_account_json'] }],
  voice: [{ id: 'twilio', name: 'Twilio Voice', detail: 'Inbound and outbound browser calls', fields: ['account_sid', 'auth_token', 'api_key', 'api_secret', 'twiml_app_sid'] }],
}

export default function ChannelsPage() {
  const { brand } = useAuth(), queryClient = useQueryClient(), [tab, setTab] = useState('sms'), [dialog, setDialog] = useState<{ channel: string; provider: string }>(), [name, setName] = useState(''), [credentials, setCredentials] = useState<Record<string, string>>({})
  const connections = useQuery({ queryKey: ['channel-connections', brand?.id], queryFn: () => get<{ data: Connection[] }>(`/api/v2/brands/${brand?.id}/connections`).then((item) => item.data), enabled: !!brand })
  const flags = useQuery({ queryKey: ['channel-flags', brand?.id], queryFn: () => get<{ data: Record<string, boolean> }>(`/api/v2/brands/${brand?.id}/feature-flags`).then((item) => item.data), enabled: !!brand })
  const create = useMutation({ mutationFn: () => post(`/api/v2/brands/${brand?.id}/connections`, { channel: dialog?.channel, provider: dialog?.provider, name: name || `${dialog?.provider} ${dialog?.channel}`, credentials, capabilities: [], is_default: true }), onSuccess: async () => { toast.success('Channel connection saved'); setDialog(undefined); setCredentials({}); await queryClient.invalidateQueries({ queryKey: ['channel-connections', brand?.id] }) }, onError: (error) => toast.error(error instanceof Error ? error.message : 'Unable to save connection') })
  const test = useMutation({ mutationFn: (id: string) => post<{ data: { ok: boolean; detail: string } }>(`/api/v2/brands/${brand?.id}/connections/${id}/test`), onSuccess: (result) => toast[result.data.ok ? 'success' : 'error'](result.data.detail), onSettled: () => queryClient.invalidateQueries({ queryKey: ['channel-connections', brand?.id] }) })
  const widgetCode = `<script async src="${window.location.origin}/api/v2/public/widget/atlas_demo/loader.js"></script>`
  return <>
    <PageHeader eyebrow={brand?.name} eyebrowTranslatable={false} title="Channels" description="Connect senders, synchronize templates, and control the brand-by-brand rollout." actions={<Button onClick={() => setDialog({ channel: tab, provider: providers[tab][0].id })}><Plus/>Add connection</Button>}/>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{['sms', 'whatsapp', 'push', 'voice'].map((channel) => { const Icon = channelIcons[channel as keyof typeof channelIcons]; const count = connections.data?.filter((item) => item.channel === channel).length ?? 0; return <Card key={channel}><CardContent className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl bg-muted"><Icon className="size-5"/></span><div><strong className="block text-sm capitalize">{channel}</strong><span className="text-xs text-muted-foreground">{count ? `${count} connection${count > 1 ? 's' : ''}` : 'Not connected'}</span></div><Badge className="ms-auto" variant={flags.data?.[channel] ? 'default' : 'secondary'}>{flags.data?.[channel] ? 'Enabled' : 'Flagged off'}</Badge></CardContent></Card> })}</div>
    <Tabs value={tab} onValueChange={(value) => setTab(String(value))}><TabsList>{['sms', 'whatsapp', 'push', 'voice', 'chat'].map((channel) => <TabsTrigger value={channel} key={channel} className="capitalize">{channel}</TabsTrigger>)}</TabsList>
      {['sms', 'whatsapp', 'push', 'voice'].map((channel) => <TabsContent key={channel} value={channel} className="mt-5 space-y-5"><div className="grid gap-4 lg:grid-cols-2">{providers[channel].map((provider) => { const existing = connections.data?.find((item) => item.channel === channel && item.provider === provider.id); return <Card key={provider.id}><CardHeader><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl border bg-muted"><Settings2 className="size-5"/></span><div><CardTitle className="text-base">{provider.name}</CardTitle><CardDescription>{provider.detail}</CardDescription></div>{existing && <Badge className="ms-auto bg-emerald-50 text-emerald-700"><CheckCircle2/>Connected</Badge>}</div></CardHeader><CardContent>{existing ? <div className="space-y-3"><div className="rounded-lg border bg-muted/30 p-3 text-xs"><div className="flex justify-between"><span className="text-muted-foreground">Connection</span><strong>{existing.name}</strong></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Status</span><strong className="capitalize">{existing.status}</strong></div><div className="mt-2 flex justify-between"><span className="text-muted-foreground">Credentials</span><span>Encrypted · never returned</span></div></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => test.mutate(existing.id)} disabled={test.isPending}><RefreshCw/>Test connection</Button><Button variant="outline" size="sm"><Webhook/>Webhook setup</Button></div></div> : <Button variant="outline" onClick={() => { setDialog({ channel, provider: provider.id }); setName(`${provider.name} ${channel}`) }}><Plus/>Connect {provider.name}</Button>}</CardContent></Card>})}</div></TabsContent>)}
      <TabsContent value="chat" className="mt-5"><Card><CardHeader><CardTitle>Embeddable web chat</CardTitle><CardDescription>The loader opens a sandboxed Sendry-hosted iframe. Add the snippet before the closing body tag on an allowed origin.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="rounded-lg border bg-slate-950 p-4 font-mono text-xs text-slate-100">{widgetCode}</div><div className="flex gap-2"><Button variant="outline" onClick={() => { void navigator.clipboard.writeText(widgetCode); toast.success('Widget code copied') }}><Copy/>Copy snippet</Button><Button variant="outline" onClick={() => window.open('/widget/atlas_demo', '_blank')}><Send/>Preview widget</Button></div><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border p-3 text-xs"><strong className="block">Signed sessions</strong><span className="text-muted-foreground">24-hour visitor tokens</span></div><div className="rounded-lg border p-3 text-xs"><strong className="block">Origin allowlist</strong><span className="text-muted-foreground">Strict browser origin checks</span></div><div className="rounded-lg border p-3 text-xs"><strong className="block">First reply claim</strong><span className="text-muted-foreground">New chats start unassigned</span></div></div></CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={!!dialog} onOpenChange={(open) => { if (!open) setDialog(undefined) }}><DialogContent><DialogHeader><DialogTitle>Connect {dialog?.provider}</DialogTitle><DialogDescription>Credentials are encrypted with AES-256-GCM. Saved secrets are never returned to this screen or written to logs.</DialogDescription></DialogHeader><div className="space-y-4"><label className="block"><Label>Connection name</Label><Input className="mt-1" value={name} onChange={(event) => setName(event.target.value)}/></label>{dialog && providers[dialog.channel]?.find((item) => item.id === dialog.provider)?.fields.map((field) => <label className="block" key={field}><Label className="capitalize">{field.replaceAll('_', ' ')}</Label><div className="relative mt-1"><KeyRound className="absolute start-3 top-2.5 size-4 text-muted-foreground"/><Input className="ps-9" type={field.includes('json') ? 'text' : 'password'} value={credentials[field] ?? ''} onChange={(event) => setCredentials((current) => ({ ...current, [field]: event.target.value }))} autoComplete="off"/></div></label>)}</div><DialogFooter><Button variant="outline" onClick={() => setDialog(undefined)}>Cancel</Button><Button onClick={() => create.mutate()} disabled={create.isPending || !dialog}>Save encrypted connection</Button></DialogFooter></DialogContent></Dialog>
  </>
}
