import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Bot, Download, ExternalLink, FileDown, MousePointerClick, RefreshCw, Share2, Sparkles, UsersRound } from 'lucide-react'
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from 'recharts'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth'
import { get, post } from '@/lib/api'
import { number, percent, shortDate } from '@/lib/format'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Progress } from '@/components/ui/progress'
import { Skeleton } from '@/components/ui/skeleton'
import { StatusBadge } from '@/components/status-badge'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

type Report = {
  campaign: { id:string;subject:string;label:string;from_name:string;from_email:string;sent_at:string;total_recipients:number;delivered:number;status:string }
  metrics: { delivered:number;deliveryRate:number;uniqueOpens:number;openRate:number;uniqueClicks:number;clickRate:number;ctor:number;unsubscribed:number;bounced:number;complaints:number }
  links: Array<{ id:string;url:string;total_clicks:number;unique_clicks:number }>
  countries: Array<{ country:string;opens:number }>
  timeline: Array<{ bucket:string;type:string;count:number }>
  recent: Array<{ id:string;type:string;occurred_at:string;name?:string;email?:string;status?:string;link_url?:string }>
  analysis?: { id:string;analysis:string;score:number;source:string }
}
type ListItem = { id: string; name: string }

export default function ReportPage() {
  const { campaignId } = useParams(); const { brand } = useAuth(); const navigate = useNavigate(); const client = useQueryClient(); const [importOpen, setImportOpen] = useState(false); const [eventType, setEventType] = useState('click'); const [listId, setListId] = useState('')
  const query = useQuery({ queryKey:['report',brand?.id,campaignId], queryFn:()=>get<Report>(`/api/brands/${brand?.id}/campaigns/${campaignId}/report`), enabled:!!brand&&!!campaignId })
  const lists = useQuery({ queryKey:['lists',brand?.id], queryFn:()=>get<ListItem[]>(`/api/brands/${brand?.id}/lists`), enabled:!!brand })
  const analyze = useMutation({ mutationFn:()=>post(`/api/brands/${brand?.id}/campaigns/${campaignId}/analyze`), onSuccess:async()=>{ await client.invalidateQueries({queryKey:['report',brand?.id,campaignId]}); toast.success('Report analysis updated') } })
  const chartData = useMemo(() => { const groups = new Map<string,Record<string,unknown>>(); for(const row of query.data?.timeline??[]){ const current=groups.get(row.bucket)??{bucket:row.bucket,delivered:0,open:0,click:0}; current[row.type]=row.count; groups.set(row.bucket,current) } return [...groups.values()] },[query.data?.timeline])
  async function duplicate(){const result=await post<{id:string}>(`/api/brands/${brand?.id}/campaigns/${campaignId}/duplicate`);navigate(`/campaigns/${result.id}`)}
  if (query.isLoading || !query.data) return <><Skeleton className="mb-6 h-20"/><Skeleton className="h-[38rem]"/></>
  const report=query.data; const total=Math.max(1,report.campaign.delivered); const maxCountry=Math.max(...report.countries.map((country)=>country.opens),1)
  return <>
    <div className="mb-5 flex flex-wrap items-start gap-3"><Button variant="ghost" size="icon-sm" onClick={()=>navigate('/reports')}><ArrowLeft/></Button><div className="mr-auto"><div className="mb-1 flex items-center gap-2"><h1 className="text-2xl font-semibold">{report.campaign.subject}</h1><StatusBadge status={report.campaign.status}/></div><p className="text-sm text-muted-foreground">Sent {shortDate(report.campaign.sent_at)} · {report.campaign.from_name} &lt;{report.campaign.from_email}&gt; · {number.format(report.campaign.total_recipients)} recipients</p></div><Button variant="outline" onClick={()=>window.open(`/api/brands/${brand?.id}/campaigns/${campaignId}/export/delivered`)}><FileDown/> Export report</Button><Button variant="outline" onClick={()=>navigator.clipboard.writeText(window.location.href)}><Share2/> Share</Button><Button variant="ghost" size="icon-sm" onClick={()=>void query.refetch()} aria-label="Refresh report"><RefreshCw/></Button></div>
    <div className="mb-5 grid overflow-hidden rounded-lg border bg-card sm:grid-cols-2 lg:grid-cols-7"><Kpi label="Delivered" value={percent(report.metrics.deliveryRate)} detail={number.format(report.metrics.delivered)}/><Kpi label="Unique opens" value={percent(report.metrics.openRate)} detail={number.format(report.metrics.uniqueOpens)}/><Kpi label="Unique clicks" value={percent(report.metrics.clickRate)} detail={number.format(report.metrics.uniqueClicks)}/><Kpi label="CTOR" value={percent(report.metrics.ctor)} detail="click-to-open"/><Kpi label="Unsubscribed" value={percent(report.metrics.unsubscribed/total*100,2)} detail={number.format(report.metrics.unsubscribed)}/><Kpi label="Bounced" value={percent(report.metrics.bounced/total*100,2)} detail={number.format(report.metrics.bounced)}/><Kpi label="Complaints" value={percent(report.metrics.complaints/total*100,2)} detail={number.format(report.metrics.complaints)}/></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_19rem]">
      <section className="space-y-5"><Card><CardHeader><CardTitle>Activity over time</CardTitle><CardDescription>Delivered messages, unique opens, and unique clicks.</CardDescription></CardHeader><CardContent><div className="h-80"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{left:-18,right:10,top:10,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="bucket" tickFormatter={(value)=>new Date(value).toLocaleTimeString('en',{hour:'2-digit',minute:'2-digit'})} tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><ChartTooltip labelFormatter={(value)=>shortDate(String(value))}/><Area type="monotone" dataKey="delivered" fill="var(--color-chart-1)" fillOpacity={.12} stroke="var(--color-chart-1)" strokeWidth={2}/><Line type="monotone" dataKey="open" stroke="var(--color-chart-2)" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="click" stroke="var(--color-chart-3)" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div></CardContent></Card>
        <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Link activity</CardTitle><CardDescription>Unique and total clicks for each tracked destination.</CardDescription></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>window.open("/api/brands/" + brand?.id + "/campaigns/" + campaignId + "/export/click")}><Download/> Export</Button><Button variant="outline" size="sm" onClick={()=>setImportOpen(true)}><UsersRound/> Import to list</Button></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>URL</TableHead><TableHead>Unique</TableHead><TableHead>Click rate</TableHead><TableHead>CTOR</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{report.links.map((link)=><TableRow key={link.id}><TableCell><a href={link.url} target="_blank" rel="noreferrer" className="inline-flex max-w-md items-center gap-1 truncate text-primary hover:underline">{link.url}<ExternalLink className="size-3"/></a></TableCell><TableCell className="tabular-nums">{number.format(link.unique_clicks)}</TableCell><TableCell className="tabular-nums">{percent(link.unique_clicks/total*100,2)}</TableCell><TableCell className="tabular-nums">{percent(link.unique_clicks/Math.max(1,report.metrics.uniqueOpens)*100,2)}</TableCell><TableCell className="tabular-nums">{number.format(link.total_clicks)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
        <Card><CardHeader><CardTitle>Recipient activity</CardTitle><CardDescription>Most recent delivery and engagement events.</CardDescription></CardHeader><CardContent><Tabs defaultValue="all"><TabsList variant="line"><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="open">Opened</TabsTrigger><TabsTrigger value="click">Clicked</TabsTrigger><TabsTrigger value="unsubscribe">Unsubscribed</TabsTrigger><TabsTrigger value="bounce">Bounced</TabsTrigger><TabsTrigger value="complaint">Complaints</TabsTrigger></TabsList>{['all','open','click','unsubscribe','bounce','complaint'].map((type)=><TabsContent key={type} value={type} className="pt-4"><div className="divide-y">{report.recent.filter((item)=>type==='all'||item.type===type).map((item)=><div key={item.id} className="flex items-center gap-3 py-3"><span className="grid size-8 place-items-center rounded-full bg-muted"><MousePointerClick className="size-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name||item.email||'Anonymous recipient'}</p><p className="truncate text-xs text-muted-foreground">{item.type}{item.link_url?` · ${item.link_url}`:''}</p></div><time className="text-xs text-muted-foreground">{shortDate(item.occurred_at)}</time></div>)}</div></TabsContent>)}</Tabs></CardContent></Card>
      </section>
      <aside className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-4 text-primary"/> Report analysis</CardTitle></CardHeader><CardContent>{report.analysis?<><div className="mx-auto mb-5 grid size-24 place-items-center rounded-full border-8 border-emerald-100"><div className="text-center"><p className="metric-number text-2xl">{report.analysis.score}</p><p className="text-[.62rem] text-muted-foreground">of 100</p></div></div><p className="text-sm leading-relaxed text-muted-foreground">{report.analysis.analysis}</p><Button variant="outline" className="mt-5 w-full" onClick={()=>analyze.mutate()} disabled={analyze.isPending}><Bot/> Re-analyse report</Button></>:<div className="text-center"><Bot className="mx-auto mb-3 size-8 text-muted-foreground"/><p className="text-sm text-muted-foreground">Turn engagement metrics into prioritized next actions.</p><Button className="mt-5 w-full" onClick={()=>analyze.mutate()} disabled={analyze.isPending}><Sparkles/> Analyze report</Button></div>}</CardContent></Card><Card><CardHeader><CardTitle>Top countries</CardTitle></CardHeader><CardContent className="space-y-4">{report.countries.length?report.countries.map((country)=><div key={country.country}><div className="mb-1 flex justify-between text-xs"><span>{country.country}</span><span className="tabular-nums text-muted-foreground">{number.format(country.opens)}</span></div><Progress value={country.opens/maxCountry*100}/></div>):<p className="text-sm text-muted-foreground">No identified country data yet.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Report actions</CardTitle></CardHeader><CardContent className="space-y-2"><Button variant="outline" className="w-full" onClick={()=>void duplicate()}><Download/> Duplicate content</Button><Button variant="outline" className="w-full" onClick={()=>window.open(`/public/campaign/${campaignId}`)}><ExternalLink/> View web version</Button></CardContent></Card></aside>
    </div>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent><DialogHeader><DialogTitle>Import campaign activity</DialogTitle><DialogDescription>Copy subscribers with a selected engagement event into an audience.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div><Label>Activity</Label><Select value={eventType} onValueChange={(value)=>setEventType(String(value))}><SelectTrigger className="mt-1.5 w-full"><SelectValue/></SelectTrigger><SelectContent>{['delivered','open','click','unsubscribe','bounce','complaint'].map((value)=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div><Label>Target audience</Label><Select value={listId||lists.data?.[0]?.id} onValueChange={(value)=>setListId(String(value))}><SelectTrigger className="mt-1.5 w-full"><SelectValue/></SelectTrigger><SelectContent>{lists.data?.map((list)=><SelectItem key={list.id} value={list.id}>{list.name}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={()=>setImportOpen(false)}>Cancel</Button><Button disabled={!lists.data?.length} onClick={async()=>{const result=await post<{imported:number}>(`/api/brands/${brand?.id}/campaigns/${campaignId}/import-activity`,{type:eventType,list_id:listId||lists.data?.[0]?.id});setImportOpen(false);toast.success(`${result.imported} subscribers imported`)}}><UsersRound/>Import activity</Button></DialogFooter></DialogContent></Dialog>
  </>
}

function Kpi({label,value,detail}:{label:string;value:string;detail:string}){return <div className="border-b p-4 last:border-b-0 sm:border-r lg:border-b-0"><p className="text-[.68rem] text-muted-foreground">{label}</p><p className="metric-number mt-2 text-xl">{value}</p><p className="mt-1 text-[.68rem] text-muted-foreground">{detail}</p></div>}
